In [1]:
import numpy as np

# NumPy Assignment – Class 4




**Topics:** Fancy Indexing, Conditional Selection, `np.sort()`, `np.argsort()`, `np.concatenate()`

Solve each question in the code cell below it.

## Q1. Create `arr = np.array([10,20,30,40,50,60,70,80])`. Print **20, 50, 80** using fancy indexing.

In [2]:
# Write your answer here
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(arr[1])
print(arr[4])
print(arr[7])
print(arr[[1, 4, 7]])

20
50
80
[20 50 80]


## Q2. Using the same array, print **10, 30, 70** and then **40, 60** using fancy indexing.

In [3]:
# Write your answer here
print(arr[[0, 2, 6]])
print(arr[[3, 5]])

[10 30 70]
[40 60]


## Q3. Create a **3×3** matrix. Print the **first row** and **third row** using fancy indexing.

In [4]:
# Write your answer here
arr2 = np.arange(1, 10).reshape(3, 3)
print(arr2, '\n')
print(arr2[[0, 2]])

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 2 3]
 [7 8 9]]


## Q4. Using the same matrix, print the **first column** and **last column** using fancy indexing.

In [5]:
# Write your answer here
print(arr2[ : , [0, 2]])

[[1 3]
 [4 6]
 [7 9]]


## Q5. Create `arr = np.array([5,12,18,7,20,25,30,2])`. Print only elements **greater than 15**.

In [6]:
# Write your answer here
arr3 = np.array([5, 12, 18, 7, 20, 25, 30, 2])
print(arr3[arr3 > 15])

[18 20 25 30]


## Q6. Using the same array, print only the **even numbers**.

In [7]:
# Write your answer here
print(arr3[arr3 % 2 == 0])

[12 18 20 30  2]


## Q7. Using the same array, print only the numbers **less than 20**.

In [8]:
# Write your answer here
print(arr3[arr3 < 20])

[ 5 12 18  7  2]


## Q8. Create `arr = np.array([18,5,27,10,3,15])`. Sort the array using `np.sort()`.

In [9]:
# Write your answer here
arr4 = np.array([18,5,27,10,3,15, 2])
print(np.sort(arr4))

[ 2  3  5 10 15 18 27]


## Q9. Using the same array, find the indices that would sort the array using `np.argsort()`.

In [10]:
# Write your answer here
print(np.argsort(arr4))

[6 4 1 3 5 0 2]


## Q10. Create `arr1 = np.array([1,2,3])` and `arr2 = np.array([4,5,6])`. Join both arrays using `np.concatenate()`.

In [11]:
# Write your answer here
arr5 = np.array([1, 2, 3])
arr6 = np.array([4, 5, 6])
print(np.concatenate((arr5, arr6)))

[1 2 3 4 5 6]
