In [1]:
import numpy as np

# NumPy Practice Questions - Set 3

Intermediate → Advanced

## Question 1

Create a (5×1) array and a (1×5) array. Use broadcasting to add them.



In [2]:
# Write your code here
arr1 = np.array([[1],[2],[3],[4],[5]])
arr2 = np.array([1, 2, 3, 4, 5])
print(arr1 + arr2)

[[ 2  3  4  5  6]
 [ 3  4  5  6  7]
 [ 4  5  6  7  8]
 [ 5  6  7  8  9]
 [ 6  7  8  9 10]]


## Question 2

Multiply a (3×1) array with a (1×4) array using broadcasting.



In [4]:
# Write your code here
arr1 = np.array([[1], [2], [3]])
arr2 = np.array([1, 2, 3, 4])
print(arr1 * arr2)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]]


## Question 3

Replace all values greater than the mean of a 5×5 matrix with the mean.


In [6]:
# Write your code here
arr = np.array([[2, 3, 34, 23, 64], [22, 23, 7, 12, 55], [23, 56, 23, 65, 23], [71, 27, 31, 83, 12], [11, 3, 19, 10, 30]])
mean = np.mean(arr)
arr[arr > mean] = int(mean)
print(arr, '\n')
print("Mean of matrix is:", int(mean))

[[ 2  3 29 23 29]
 [22 23  7 12 29]
 [23 29 23 29 23]
 [29 27 29 29 12]
 [11  3 19 10 29]] 

Mean of matrix is: 29


## Question 4

Use `np.where()` to square even numbers and cube odd numbers.


In [ ]:
# Write your code here
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
condition = np.where(arr % 2 == 0, arr ** 2, arr ** 3)
print(condition)

[[   1    4   27   16  125]
 [  36  343   64  729  100]
 [1331  144 2197  196 3375]]


## Question 5

Find indices of elements divisible by both 3 and 5.


In [14]:
# Write your code here
arr = np.array([
    [
        [2, 3, 34, 23, 64],
    [22, 23, 15, 12, 55],
    [30, 56, 20, 65, 23],
    [71, 27, 45, 83, 12],
    [11, 3, 19, 10, 30]
    ],

    [
    [2, 3, 34, 23, 64],
    [22, 23, 15, 12, 55],
    [30, 56, 20, 65, 23],
    [71, 27, 45, 83, 12],
    [11, 3, 19, 10, 30]
    ]
])

indices = np.where((arr % 3 == 0) & (arr % 5 == 0))
print(indices)

(array([1, 2, 3, 4]), array([2, 0, 2, 4]))


## Question 6

Extract all elements on and above the main diagonal of a 6×6 matrix.



In [15]:
# Write your code here
arr = np.array([
    [2, 3, 34, 23, 64],
    [22, 23, 15, 12, 55],
    [30, 56, 20, 65, 23],
    [71, 27, 45, 83, 12],
    [11, 3, 19, 10, 30]
])
print(np.triu(arr))
# We can use k = () to getting adjust the matrix

[[ 2  3 34 23 64]
 [ 0 23 15 12 55]
 [ 0  0 20 65 23]
 [ 0  0  0 83 12]
 [ 0  0  0  0 30]]


## Question 7

Extract all elements below the main diagonal.



In [16]:
# Write your code here
print(np.tril(arr, k = -1))
# We can use k = () to getting adjust the matrix

[[ 0  0  0  0  0]
 [22  0  0  0  0]
 [30 56  0  0  0]
 [71 27 45  0  0]
 [11  3 19 10  0]]


## Question 8

Create an 8×8 checkerboard using slicing (no loops).


In [ ]:
# Write your code here
arr = np.zeros((8, 8), dtype = int)

arr[::2, 1::2] = 1
arr[1::2, ::2] = 1
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Question 9

Reverse a 2D array row-wise and column-wise.


In [23]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr, "\n")
print("Row wise reverse\n", arr[:, ::-1], "\n")
print("Column wise reverse\n", arr[::-1, ::])

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

Row wise reverse
 [[3 2 1]
 [6 5 4]
 [9 8 7]] 

Column wise reverse
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


## Question 10

Find common elements between two arrays and elements unique to the first array.


In [25]:
# Write your code here
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[5, 6, 7], [8, 9, 1]])
print("Common Elements Are:", np.intersect1d(arr1, arr2))
print("Unique In First Array:", np.setdiff1d(arr1, arr2))

Common Elements Are: [1 5 6]
Unique In First Array: [2 3 4]


## Question 11

Find the second smallest and second largest unique values in an array.



In [31]:
from enum import unique
# Write your code here
arr = np.array([[2, 5, 6], [1, 7, 3], [8, 9, 4]])
unique_element = np.unique(arr)
print("Second Largest Element:", unique_element[1])
print("Second Smallest Element:", unique_element[-2])

Second Largest Element: 2
Second Smallest Element: 8


## Question 12

Swap the first and last rows of a matrix.


In [33]:
# Write your code here
arr[[0, -1]] = arr[[-1, 0]]
print(arr)

[[8 9 4]
 [1 7 3]
 [2 5 8]]
