In [1]:
import numpy as np

# NumPy Practice — Part 1: Fundamentals

**Target:** Beginner Data Analyst / Data Scientist

This part builds the core NumPy skills you should be fluent with before moving to Pandas:
- array creation
- attributes and data types
- indexing and slicing
- reshaping, flattening and transpose
- vectorized arithmetic
- basic aggregation and statistics


## 1. Array Creation

**Q1.** Import NumPy as np and print its version.

In [2]:
# Write your solution here
print(np.__version__)

2.1.3


**Q2.** Create a NumPy array from [10, 20, 30, 40, 50].

In [3]:
# Write your solution here
arr = np.array([10, 20, 30, 40, 50])
arr

array([10, 20, 30, 40, 50])

**Q3.** Create an array containing integers from 1 to 20.

In [4]:
# Write your solution here
arr = np.arange(1, 21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

**Q4.** Create an array containing even numbers from 2 to 50.

In [5]:
# Write your solution here
arr = np.arange(2, 51, 2)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

**Q5.** Create an array of 10 zeros.

In [6]:
# Write your solution here
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Q6.** Create an array of 10 ones.

In [7]:
# Write your solution here
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

**Q7.** Create a 3 × 4 array of zeros.

In [8]:
# Write your solution here
arr = np.zeros([3, 4])
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**Q8.** Create a 3 × 4 array filled with 5.

In [9]:
# Write your solution here
arr = np.full([3, 4], 5)
arr

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

**Q9.** Create a 4 × 4 identity matrix.

In [10]:
# Write your solution here
arr = np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**Q10.** Create 10 equally spaced values between 0 and 1.

In [11]:
# Write your solution here
arr = np.linspace(0, 1, 10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

**Q11.** Create numbers from 1 to 12 and reshape them into a 3 × 4 matrix.

In [12]:
# Write your solution here
arr = np.arange(1, 13).reshape(3, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**Q12.** Create an array of five random integers between 1 and 100.

In [13]:
# Write your solution here
arr = np.random.randint(1, 100, 5)
arr

array([20, 26, 36, 84, 33])

## 2. Attributes & Data Types

**Q1.** Create a 2-D array and display ndim, shape, size and dtype.

In [14]:
# Write your solution here
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.ndim(arr))
print(np.shape(arr))
print(np.size(arr))
print(arr.dtype)

2
(2, 3)
6
int64


**Q2.** Find the number of elements in a 5 × 6 array.

In [15]:
# Write your solution here
arr = np.random.randint(1, 100, 30).reshape(5, 6)
print(f"Number of element: {np.size(arr)}")

Number of element: 30


**Q3.** Create an integer array and inspect its dtype.

In [16]:
# Write your solution here
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int64


**Q4.** Create a float array and inspect its dtype.

In [17]:
# Write your solution here
arr = np.array([1.2, 2.3, 3.4, 4.5])
print(arr.dtype)

float64


**Q5.** Convert an integer array to float.

In [18]:
# Write your solution here
arr = np.array([1, 2, 3, 4, 5])
arr = arr.astype(float)
print(arr)
print(arr.dtype)

[1. 2. 3. 4. 5.]
float64


**Q6.** Convert a float array to integer.

In [19]:
# Write your solution here
arr = np.array([1.2, 2.3, 3.4, 4.5])
print(arr.dtype)
arr = arr.astype(int)
print(arr.dtype)

float64
int64


**Q7.** Compare the shapes of two arrays.

In [20]:
# Write your solution here
arr = np.array([1, 2, 4])
arr1 = np.array([[1, 2, 3], [2, 34, 64]])
print(f"arr shape is: {np.shape(arr)}")
print(f"arr1 shape is: {np.shape(arr1)}")

arr shape is: (3,)
arr1 shape is: (2, 3)


**Q8.** Create a Boolean array and inspect its dtype.

In [21]:
# Write your solution here
arr = np.array([True, True, False, False, True])
print(arr.dtype)

bool


**Q9.** Find the memory size of an array using nbytes.

In [22]:
# Write your solution here
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.nbytes)

48


## 3. Indexing

**Q1.** Get the first element of an array.

In [23]:
# Write your solution here
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr[0])

1


**Q2.** Get the last element using negative indexing.

In [24]:
# Write your solution here
print(arr[-1])

8


**Q3.** Get the first three elements.

In [25]:
# Write your solution here
print(arr[0:3])

[1 2 3]


**Q4.** Get every second element.

In [26]:
# Write your solution here
print(arr[::2])

[1 3 5 7]


**Q5.** Create a 4 × 5 matrix and access row 2, column 3.

In [27]:
# Write your solution here
arr = np.random.randint(1, 100, 20).reshape(4, 5)
print(arr, '\n')
print("Row NO 2: ", arr[1], '\n')
print("Column No 3: ", arr[:,2])

[[21 41  2 31 52]
 [24 93 99 89 93]
 [31 67 48 72 55]
 [47  2 10 88 36]] 

Row NO 2:  [24 93 99 89 93] 

Column No 3:  [ 2 99 48 10]


**Q6.** Get the first row.

In [28]:
# Write your solution here
print(arr[0])

[21 41  2 31 52]


**Q7.** Get the last row.

In [29]:
# Write your solution here
print(arr[-1])

[47  2 10 88 36]


**Q8.** Get the first column.

In [30]:
# Write your solution here
print(arr[:, 0])

[21 24 31 47]


**Q9.** Get the last column.

In [31]:
# Write your solution here
print(arr[:, -1])

[52 93 55 36]


**Q10.** Replace one element in a matrix.

In [32]:
# Write your solution here
print(arr[0, 0], "change this first no to 1000")
arr[0, 0] = 1000
print(arr[0, 0])

21 change this first no to 1000
1000


**Q11.** Replace an entire row.

In [33]:
# Write your solution here
print(arr[1])
arr[1] = [-1, -2, -3, -4, -5]
print(arr[1])

[24 93 99 89 93]
[-1 -2 -3 -4 -5]


**Q12.** Replace an entire column.

In [34]:
# Write your solution here
print(arr[ : , 3])
arr[ : , 3] = [1000, 2000, 3000, 4000]
print(arr[ : , 3])

[31 -4 72 88]
[1000 2000 3000 4000]


In [35]:
print("After all this changes our matrix become\n")
print(arr)

After all this changes our matrix become

[[1000   41    2 1000   52]
 [  -1   -2   -3 2000   -5]
 [  31   67   48 3000   55]
 [  47    2   10 4000   36]]


## 4. Slicing

**Q1.** Reverse a 1-D array using slicing.

In [36]:
# Write your solution here
arr = np.array([1, 2, 3, 4, 5])
print(arr[::-1])

[5 4 3 2 1]


**Q2.** Extract rows 2 to 4 from a matrix.

In [37]:
# Write your solution here
arr = np.random.randint(1, 100, 20).reshape(5, 4)
print(arr, '\n')
print(arr[1:4])

[[60  2 47 94]
 [29 44 90 24]
 [71 39 71  2]
 [12 42  3 80]
 [26 41 13 78]] 

[[29 44 90 24]
 [71 39 71  2]
 [12 42  3 80]]


**Q3.** Extract columns 2 to 4.

In [38]:
# Write your solution here
print(arr[ : , 1:4])

[[ 2 47 94]
 [44 90 24]
 [39 71  2]
 [42  3 80]
 [41 13 78]]


**Q4.** Extract a 2 × 2 submatrix.

In [39]:
# Write your solution here
print(arr[ 1:3, 1:3 ])

[[44 90]
 [39 71]]


**Q5.** Select every second row.

In [40]:
# Write your solution here
print(arr[::2])

[[60  2 47 94]
 [71 39 71  2]
 [26 41 13 78]]


**Q6.** Select every second column.

In [41]:
# Write your solution here
print(arr[ : , ::2])

[[60 47]
 [29 90]
 [71 71]
 [12  3]
 [26 13]]


**Q7.** Select every second row and every second column.

In [42]:
# Write your solution here
print(arr[ ::2, ::2])

[[60 47]
 [71 71]
 [26 13]]


**Q8.** Create a slice from index 2 to the end.

In [43]:
# Write your solution here
arr = np.array([2, 23, 24, 35, 37, 40, 41, 42, 44, 47, 50])
print(arr[2: ])

[24 35 37 40 41 42 44 47 50]


**Q9.** Create a reverse slice from index 8 down to index 2.

In [44]:
# Write your solution here
print(arr[8:1:-1])

[44 42 41 40 37 35 24]


## 5. Reshape, Flatten & Transpose

**Q1.** Reshape 12 elements into a 3 × 4 matrix.

In [45]:
# Write your solution here
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]).reshape(3, 4)
print(arr, '\n')
print(arr.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

(3, 4)


**Q2.** Reshape 12 elements into a 2 × 6 matrix.

In [46]:
# Write your solution here
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]).reshape(2, 6)
print(arr, '\n')
print(arr.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] 

(2, 6)


**Q3.** Reshape into a 2 × 2 × 3 array.

In [47]:
# Write your solution here
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]).reshape(2, 2, 3)
print(arr, '\n')
print(arr.shape, '\n')
print(arr.ndim, '\n')
print(arr.size)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 

(2, 2, 3) 

3 

12


**Q4.** Use reshape(-1) to convert a matrix to 1-D.

In [48]:
# Write your solution here
arr.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

**Q5.** Use flatten() to convert a matrix to 1-D.

In [49]:
# Write your solution here
print(arr, '\n')
arr.flatten()

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

**Q6.** Use ravel() to convert a matrix to 1-D.

In [50]:
# Write your solution here
print(arr, '\n')
print(np.ravel(arr))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 

[ 1  2  3  4  5  6  7  8  9 10 11 12]


**Q7.** Compare flatten() and ravel() by modifying their results.

In [51]:
# Write your solution here
print(arr.flatten())
print(np.ravel(arr))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


**Q8.** Transpose a matrix using .T.

In [52]:
# Write your solution here
arr = np.array([[2, 4, 6], [8, 10, 12]])
print(arr.T)

[[ 2  8]
 [ 4 10]
 [ 6 12]]


**Q9.** Transpose a matrix using transpose().

In [53]:
# Write your solution here
np.transpose(arr)

array([[ 2,  8],
       [ 4, 10],
       [ 6, 12]])

**Q10.** Reshape a dataset so rows represent observations and columns represent features.

In [54]:
# Write your solution here
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


## 6. Vectorized Arithmetic

**Q1.** Add 10 to every value in an array.

In [55]:
# Write your solution here
arr = np.array([1, 4, 7, 21, 7, 34, 10])
print(arr + 10)

[11 14 17 31 17 44 20]


**Q2.** Multiply every value by 2.

In [56]:
# Write your solution here
print(arr * 2)

[ 2  8 14 42 14 68 20]


**Q3.** Calculate the square of every value.

In [57]:
# Write your solution here
print(arr ** 2)

[   1   16   49  441   49 1156  100]


**Q4.** Calculate the square root of every value.

In [58]:
# Write your solution here
arr = np.array([1, 4, 9, 16, 25, 36])
print(np.sqrt(arr))

[1. 2. 3. 4. 5. 6.]


**Q5.** Increase every value by 10%.

In [59]:
# Write your solution here
arr = np.array([1, 4, 7, 21, 7, 34, 10])
print(arr * 1.10)

[ 1.1  4.4  7.7 23.1  7.7 37.4 11. ]


**Q6.** Given quantity and price arrays, calculate revenue for every product.

In [60]:
# Write your solution here
quantity = np.array([10, 20, 5])
price = np.array([100, 200, 300])
revenue = quantity * price
print(revenue)

[1000 4000 1500]


**Q7.** Given salaries, calculate a 15% bonus for every employee.

In [61]:
# Write your solution here
salaries = np.array([10000, 25000, 32000, 45000, 50000])
bonus = salaries * 0.15
print(bonus)

[1500. 3750. 4800. 6750. 7500.]


**Q8.** Given marks out of 100, calculate percentages without a loop.

In [62]:
# Write your solution here
marks = np.array([45, 60, 75, 90])
total = 100

percentage = (marks / total) * 100
print(percentage)

[45. 60. 75. 90.]


**Q9.** Calculate the difference between two temperature arrays.

In [63]:
# Write your solution here
temp1 = np.array([30, 35, 28, 32])
temp2 = np.array([25, 30, 30, 27])

difference = temp1 - temp2
print(difference)

[ 5  5 -2  5]


**Q10.** Calculate percentage change between old and new prices.

In [64]:
# Write your solution here
old_price = np.array([100, 200, 500])
new_price = np.array([120, 180, 550])

percentage_change = ((new_price - old_price) / old_price) * 100
print(percentage_change)

[ 20. -10.  10.]


**Q11.** Round a floating-point array to two decimal places.

In [65]:
# Write your solution here
arr = np.array([1.23456, 2.67891, 3.45678])

print(np.round(arr, 2))

[1.23 2.68 3.46]


## 7. Basic Aggregation & Statistics

**Q1.** Calculate the sum of an array.

In [66]:
# Write your solution here
arr = np.array([12, 15, 18, 20, 22, 25, 28, 30, 32, 35])
print(np.sum(arr))

237


**Q2.** Calculate the mean.

In [67]:
# Write your solution here
print(np.mean(arr))

23.7


**Q3.** Calculate the median.

In [68]:
# Write your solution here
print(np.mean(arr))

23.7


**Q4.** Find the minimum and maximum.

In [69]:
# Write your solution here
print(np.min(arr))
print(np.max(arr))

12
35


**Q5.** Find argmin() and argmax().

In [70]:
# Write your solution here
print(np.argmin(arr))
print(np.argmax(arr))

0
9


**Q6.** Calculate standard deviation.

In [71]:
# Write your solution here
print(np.std(arr))

7.197916365171244


**Q7.** Calculate variance.

In [72]:
# Write your solution here
np.var(arr)

np.float64(51.81)

**Q8.** Calculate the range.

In [73]:
# Write your solution here
np.max(arr) - np.min(arr)

np.int64(23)

**Q9.** Calculate the 25th, 50th and 75th percentiles.

In [74]:
# Write your solution here
print(np.percentile(arr, 25))
print(np.percentile(arr, 50))
print(np.percentile(arr, 75))

18.5
23.5
29.5


**Q10.** Calculate cumulative sum.

In [75]:
# Write your solution here
np.cumsum(arr)

array([ 12,  27,  45,  65,  87, 112, 140, 170, 202, 237])

**Q11.** Given student marks, calculate class total and average.

In [76]:
# Write your solution here
marks = np.array([75, 80, 65, 90, 70])

class_total = np.sum(marks)
class_average = np.mean(marks)

print("Class Total:", class_total)
print("Class Average:", class_average)

Class Total: 380
Class Average: 76.0


**Q12.** Given employee salaries, calculate average, minimum and maximum.

In [77]:
# Write your solution here
salaries = np.array([25000, 30000, 45000, 50000, 35000])

average = np.mean(salaries)
minimum = np.min(salaries)
maximum = np.max(salaries)

print("Average:", average)
print("Minimum:", minimum)
print("Maximum:", maximum)

Average: 37000.0
Minimum: 25000
Maximum: 50000


**Q13.** Given daily sales, find the best and worst sales day.

In [78]:
# Write your solution here
sales = np.array([1200, 1500, 900, 1800, 1100, 2000, 1300])

best_day = np.argmax(sales)
worst_day = np.argmin(sales)

print("Best day:", best_day + 1)
print("Best sales:", sales[best_day])

print("Worst day:", worst_day + 1)
print("Worst sales:", sales[worst_day])

Best day: 6
Best sales: 2000
Worst day: 3
Worst sales: 900


# Part 1 Completion Checklist

- [ ] I can solve these questions without copying code.
- [ ] I understand why the NumPy operation works.
- [ ] I can solve similar problems with a new dataset.
- [ ] I can avoid unnecessary Python loops through vectorization.

**Questions in this part:** 77

**Next:** Move to the next part only after you can solve most questions independently.
