# Final NumPy Assignment (Classes 1–4)

### Instructions
- Solve all questions.
- Write your code in the code cell below each question.
- Do not modify the questions.
- Total Questions: **30**


In [1]:
import numpy as np

# Part A – Array Creation

### Q1. Create a NumPy array from the list `[5,10,15,20,25]`.

In [2]:
# Write your answer here
arr = np.arange(5, 26, 5)
print(arr)

[ 5 10 15 20 25]


### Q2. Create a **3×4** array of zeros.

In [3]:
# Write your answer here
arr = np.zeros((3, 4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Q3. Create a **4×4** array of ones.

In [4]:
# Write your answer here
arr = np.ones((4, 4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Q4. Create a **5×5 identity matrix** using `np.eye()`.

In [5]:
# Write your answer here
arr = np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Q5. Create an array from **1 to 50** with a step of **5**.

In [6]:
# Write your answer here
arr = np.arange(1, 51, 5)
print(arr)

[ 1  6 11 16 21 26 31 36 41 46]


# Part B – Array Attributes

In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# arr = np.arange(1, 10).reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Q6. Find the **shape** of the given array.

In [8]:
# Write your answer here
print(arr.shape)

(3, 3)


### Q7. Find the **number of dimensions (`ndim`)**.

In [9]:
# Write your answer here
print(arr.ndim)

2


### Q8. Find the **total number of elements (`size`)**.

In [10]:
# Write your answer here
print(arr.size)

9


### Q9. Find the **data type (`dtype`)**.

In [11]:
# Write your answer here
print(arr.dtype)

int64


### Q10. Convert the array into **float** datatype.

In [12]:
# Write your answer here
new_arr = arr.astype(float)
print(new_arr, '\n')
print(new_arr.dtype)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] 

float64


# Part C – Indexing & Slicing

### Q11. Print the **first element** of a 1D array.

In [13]:
# Write your answer here
arr = np.arange(1, 11)
print(arr[0])

1


### Q12. Print the **last element** of a 1D array.

In [14]:
# Write your answer here
print(arr[-1])

10


### Q13. Print the **first row** of a 2D array.

In [15]:
# Write your answer here
arr = np.arange(1, 10).reshape(3, 3)
print(arr[0])

[1 2 3]


### Q14. Print the **last column** of a 2D array.

In [16]:
# Write your answer here
print(arr[ : , 2])

[3 6 9]


### Q15. Print elements from **index 2 to 7**.

In [17]:
# Write your answer here
arr = np.arange(1, 11)
print(arr[[2, 3, 4, 5, 6, 7]])

[3 4 5 6 7 8]


### Q16. Reverse the array using slicing.

In [18]:
# Write your answer here
print(arr[::-1])

[10  9  8  7  6  5  4  3  2  1]


# Part D – Reshape & Flatten

### Q17. Convert a 1D array of **12 elements** into a **3×4** matrix.

In [19]:
# Write your answer here
arr = np.arange(1, 13)
print(arr.reshape(3, 4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Q18. Reshape the above matrix into **2×6**.

In [20]:
# Write your answer here
print(arr.reshape(2, 6))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


### Q19. Flatten the matrix using `flatten()`.

In [21]:
# Write your answer here
print(arr.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


### Q20. Reshape the array into **4×3**.

In [22]:
# Write your answer here
print(arr.reshape(4, 3))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Part E – Broadcasting & Arithmetic

### Q21. Add **10** to every element of an array.

In [23]:
# Write your answer here
print(arr + 10)

[11 12 13 14 15 16 17 18 19 20 21 22]


### Q22. Multiply every element by **5**.

In [24]:
# Write your answer here
print(arr * 5)

[ 5 10 15 20 25 30 35 40 45 50 55 60]


### Q23. Add two arrays element-wise.

In [25]:
# Write your answer here
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
print(arr1 + arr2)

[ 6  8 10 12]


### Q24. Find the square of every element.

In [26]:
# Write your answer here
print(arr1 ** 2)

[ 1  4  9 16]


# Part F – Fancy & Boolean Indexing

In [27]:
arr_1d = np.arange(10, 101, 10)

In [28]:
arr_2d = np.arange(1, 10).reshape(3, 3)

### Q25. Using fancy indexing, print **20, 40, 80** from a 1D array.

In [29]:
# Write your answer here
print(arr[[1, 3, 7]])

[2 4 8]


### Q26. Using fancy indexing, print the **first and third rows** of a 2D array.

In [30]:
# Write your answer here
print(arr_2d[0])
print(arr_2d[2])

[1 2 3]
[7 8 9]


### Q27. Using boolean indexing, print elements **greater than 20**.

In [31]:
# Write your answer here
print(arr > 20)

[False False False False False False False False False False False False]


### Q28. Using boolean indexing, print only the **even numbers**.

In [32]:
# Write your answer here
print( arr_2d % 2 == 0 )

[[False  True False]
 [ True False  True]
 [False  True False]]


# Part G – Sorting & Concatenation

In [33]:
arr = np.array([43, 12, 23, 86, 34, 76, 28, 37, 94, 20])

### Q29. Sort an array using `np.sort()`.

In [34]:
# Write your answer here
print(np.sort(arr))

[12 20 23 28 34 37 43 76 86 94]


### Q30. Find the sorted indices using `np.argsort()`.

In [35]:
# Write your answer here
print(np.argsort(arr))

[1 9 2 6 4 7 0 5 3 8]


### Q31. Join two arrays using `np.concatenate()`.

In [36]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [37]:
# Write your answer here
print(np.concatenate([arr1, arr2]))

[1 2 3 4 5 6]
