In [182]:
import numpy as np

# NumPy Practice — Part 1: Fundamentals

**Target:** Beginner Data Analyst / Data Scientist

This part builds the core NumPy skills you should be fluent with before moving to Pandas:
- array creation
- attributes and data types
- indexing and slicing
- reshaping, flattening and transpose
- vectorized arithmetic
- basic aggregation and statistics


## 1. Array Creation

**Q1.** Import NumPy as np and print its version.

In [183]:
# Write your solution here
print(np.__version__)

2.1.3


**Q2.** Create a NumPy array from [10, 20, 30, 40, 50].

In [184]:
# Write your solution here
arr = np.array([10, 20, 30, 40, 50])
arr

array([10, 20, 30, 40, 50])

**Q3.** Create an array containing integers from 1 to 20.

In [185]:
# Write your solution here
arr = np.arange(1, 21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

**Q4.** Create an array containing even numbers from 2 to 50.

In [186]:
# Write your solution here
arr = np.arange(2, 51, 2)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

**Q5.** Create an array of 10 zeros.

In [187]:
# Write your solution here
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Q6.** Create an array of 10 ones.

In [188]:
# Write your solution here
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

**Q7.** Create a 3 × 4 array of zeros.

In [189]:
# Write your solution here
arr = np.zeros([3, 4])
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**Q8.** Create a 3 × 4 array filled with 5.

In [190]:
# Write your solution here
arr = np.full([3, 4], 5)
arr

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

**Q9.** Create a 4 × 4 identity matrix.

In [191]:
# Write your solution here
arr = np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**Q10.** Create 10 equally spaced values between 0 and 1.

In [192]:
# Write your solution here
arr = np.linspace(0, 1, 10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

**Q11.** Create numbers from 1 to 12 and reshape them into a 3 × 4 matrix.

In [193]:
# Write your solution here
arr = np.arange(1, 13).reshape(3, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**Q12.** Create an array of five random integers between 1 and 100.

In [194]:
# Write your solution here
arr = np.random.randint(1, 100, 5)
arr

array([95, 36, 79, 13, 83])

## 2. Attributes & Data Types

**Q1.** Create a 2-D array and display ndim, shape, size and dtype.

In [195]:
# Write your solution here
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.ndim(arr))
print(np.shape(arr))
print(np.size(arr))
print(arr.dtype)

2
(2, 3)
6
int64


**Q2.** Find the number of elements in a 5 × 6 array.

In [196]:
# Write your solution here
arr = np.random.randint(1, 100, 30).reshape(5, 6)
print(f"Number of element: {np.size(arr)}")

Number of element: 30


**Q3.** Create an integer array and inspect its dtype.

In [197]:
# Write your solution here
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int64


**Q4.** Create a float array and inspect its dtype.

In [198]:
# Write your solution here
arr = np.array([1.2, 2.3, 3.4, 4.5])
print(arr.dtype)

float64


**Q5.** Convert an integer array to float.

In [199]:
# Write your solution here
arr = np.array([1, 2, 3, 4, 5])
arr = arr.astype(float)
print(arr)
print(arr.dtype)

[1. 2. 3. 4. 5.]
float64


**Q6.** Convert a float array to integer.

In [200]:
# Write your solution here
arr = np.array([1.2, 2.3, 3.4, 4.5])
print(arr.dtype)
arr = arr.astype(int)
print(arr.dtype)

float64
int64


**Q7.** Compare the shapes of two arrays.

In [201]:
# Write your solution here
arr = np.array([1, 2, 4])
arr1 = np.array([[1, 2, 3], [2, 34, 64]])
print(f"arr shape is: {np.shape(arr)}")
print(f"arr1 shape is: {np.shape(arr1)}")

arr shape is: (3,)
arr1 shape is: (2, 3)


**Q8.** Create a Boolean array and inspect its dtype.

In [202]:
# Write your solution here
arr = np.array([True, True, False, False, True])
print(arr.dtype)

bool


**Q9.** Find the memory size of an array using nbytes.

In [203]:
# Write your solution here
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.nbytes)

48


## 3. Indexing

**Q1.** Get the first element of an array.

In [204]:
# Write your solution here
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr[0])

1


**Q2.** Get the last element using negative indexing.

In [205]:
# Write your solution here
print(arr[-1])

8


**Q3.** Get the first three elements.

In [206]:
# Write your solution here
print(arr[0:3])

[1 2 3]


**Q4.** Get every second element.

In [207]:
# Write your solution here
print(arr[::2])

[1 3 5 7]


**Q5.** Create a 4 × 5 matrix and access row 2, column 3.

In [208]:
# Write your solution here
arr = np.random.randint(1, 100, 20).reshape(4, 5)
print(arr, '\n')
print("Row NO 2: ", arr[1], '\n')
print("Column No 3: ", arr[:,2])

[[99 60 22 55 37]
 [ 1 98 83 14 26]
 [71 37 39 71 44]
 [21 40 83 80 64]] 

Row NO 2:  [ 1 98 83 14 26] 

Column No 3:  [22 83 39 83]


**Q6.** Get the first row.

In [209]:
# Write your solution here
print(arr[0])

[99 60 22 55 37]


**Q7.** Get the last row.

In [210]:
# Write your solution here
print(arr[-1])

[21 40 83 80 64]


**Q8.** Get the first column.

In [211]:
# Write your solution here
print(arr[:, 0])

[99  1 71 21]


**Q9.** Get the last column.

In [212]:
# Write your solution here
print(arr[:, -1])

[37 26 44 64]


**Q10.** Replace one element in a matrix.

In [213]:
# Write your solution here
print(arr[0, 0], "change this first no to 1000")
arr[0, 0] = 1000
print(arr[0, 0])

99 change this first no to 1000
1000


**Q11.** Replace an entire row.

In [214]:
# Write your solution here
print(arr[1])
arr[1] = [-1, -2, -3, -4, -5]
print(arr[1])

[ 1 98 83 14 26]
[-1 -2 -3 -4 -5]


**Q12.** Replace an entire column.

In [236]:
# Write your solution here
print(arr[ : , 3])
arr[ : , 3] = [1000, 2000, 3000, 4000]
print(arr[ : , 3])

[55 -4 71 80]
[1000 2000 3000 4000]


In [237]:
print("After all this changes our matrix become\n")
print(arr)

After all this changes our matrix become

[[1000   60   22 1000   37]
 [  -1   -2   -3 2000   -5]
 [  71   37   39 3000   44]
 [  21   40   83 4000   64]]


## 4. Slicing

**Q1.** Reverse a 1-D array using slicing.

In [ ]:
# Write your solution here


**Q2.** Extract rows 2 to 4 from a matrix.

In [ ]:
# Write your solution here


**Q3.** Extract columns 2 to 4.

In [ ]:
# Write your solution here


**Q4.** Extract a 2 × 2 submatrix.

In [ ]:
# Write your solution here


**Q5.** Select every second row.

In [ ]:
# Write your solution here


**Q6.** Select every second column.

In [ ]:
# Write your solution here


**Q7.** Select every second row and every second column.

In [ ]:
# Write your solution here


**Q8.** Create a slice from index 2 to the end.

In [ ]:
# Write your solution here


**Q9.** Create a reverse slice from index 8 down to index 2.

In [ ]:
# Write your solution here


## 5. Reshape, Flatten & Transpose

**Q1.** Reshape 12 elements into a 3 × 4 matrix.

In [ ]:
# Write your solution here


**Q2.** Reshape 12 elements into a 2 × 6 matrix.

In [ ]:
# Write your solution here


**Q3.** Reshape into a 2 × 2 × 3 array.

In [ ]:
# Write your solution here


**Q4.** Use reshape(-1) to convert a matrix to 1-D.

In [ ]:
# Write your solution here


**Q5.** Use flatten() to convert a matrix to 1-D.

In [ ]:
# Write your solution here


**Q6.** Use ravel() to convert a matrix to 1-D.

In [ ]:
# Write your solution here


**Q7.** Compare flatten() and ravel() by modifying their results.

In [ ]:
# Write your solution here


**Q8.** Transpose a matrix using .T.

In [ ]:
# Write your solution here


**Q9.** Transpose a matrix using transpose().

In [ ]:
# Write your solution here


**Q10.** Reshape a dataset so rows represent observations and columns represent features.

In [ ]:
# Write your solution here


## 6. Vectorized Arithmetic

**Q1.** Add 10 to every value in an array.

In [ ]:
# Write your solution here


**Q2.** Multiply every value by 2.

In [ ]:
# Write your solution here


**Q3.** Calculate the square of every value.

In [ ]:
# Write your solution here


**Q4.** Calculate the square root of every value.

In [ ]:
# Write your solution here


**Q5.** Increase every value by 10%.

In [216]:
# Write your solution here


**Q6.** Given quantity and price arrays, calculate revenue for every product.

In [217]:
# Write your solution here


**Q7.** Given salaries, calculate a 15% bonus for every employee.

In [218]:
# Write your solution here


**Q8.** Given marks out of 100, calculate percentages without a loop.

In [219]:
# Write your solution here


**Q9.** Calculate the difference between two temperature arrays.

In [220]:
# Write your solution here


**Q10.** Calculate percentage change between old and new prices.

In [221]:
# Write your solution here


**Q11.** Round a floating-point array to two decimal places.

In [222]:
# Write your solution here


## 7. Basic Aggregation & Statistics

**Q1.** Calculate the sum of an array.

In [223]:
# Write your solution here


**Q2.** Calculate the mean.

In [224]:
# Write your solution here


**Q3.** Calculate the median.

In [225]:
# Write your solution here


**Q4.** Find the minimum and maximum.

In [226]:
# Write your solution here


**Q5.** Find argmin() and argmax().

In [227]:
# Write your solution here


**Q6.** Calculate standard deviation.

In [228]:
# Write your solution here


**Q7.** Calculate variance.

In [229]:
# Write your solution here


**Q8.** Calculate the range.

In [230]:
# Write your solution here


**Q9.** Calculate the 25th, 50th and 75th percentiles.

In [231]:
# Write your solution here


**Q10.** Calculate cumulative sum.

In [232]:
# Write your solution here


**Q11.** Given student marks, calculate class total and average.

In [233]:
# Write your solution here


**Q12.** Given employee salaries, calculate average, minimum and maximum.

In [234]:
# Write your solution here


**Q13.** Given daily sales, find the best and worst sales day.

In [235]:
# Write your solution here


# Part 1 Completion Checklist

- [ ] I can solve these questions without copying code.
- [ ] I understand why the NumPy operation works.
- [ ] I can solve similar problems with a new dataset.
- [ ] I can avoid unnecessary Python loops through vectorization.

**Questions in this part:** 77

**Next:** Move to the next part only after you can solve most questions independently.
